name: PR Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install dependencies
      run: npm ci
    - name: Run ESLint
      run: npx eslint src
    - name: Run Prettier
      run: npx prettier -c src
